"use client"
import { Inter } from "next/font/google";
import "./globals.css";



// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { Provider } from "react-redux";
import store from "./store/store";

 const  RootLayout = ({ children , pageProps})=> {
  return (
    <html lang="en">
      <body>

        <Provider store={store} >
        {children}
        </Provider>
        </body>
    </html>
  );
  }

  export default RootLayout